travis build
pear/pearweb_phars pull request #1
Opened 2017-03-22 19:31 UTC by ashnazg

This `run-installer.sh` script works for me on Ubuntu Trusty using PHP 5.5 and 5.6.  It successfully runs the `go-pear.phar` installation without requiring user input.

What I cannot figure out is why Travis appears to run it cleanly, but then doesn't have the PEAR installation available.

Right now, the invocation of the `run-installer.sh` should be doing the install.  The later `php go-pear.phar` is solely to show you the paths it defaults to, which is presumably where the first invocation should have installed it.  Note the build will get stuck here, waiting for user input, so it must be manually canceled or else wait until Travis time-limits the build and kills it.

@kenguest , @till , @cweiske , could you guys try out the `run-installer.sh` script locally to confirm it works in your environments?

More importantly, who could shed some light on why Travis is behaving like it does?  I don't understand why the PEAR installation doesn't properly appear in `/home/travis/pear`, based on the default pathing shown.

2017-03-23 13:36 UTC, till requested changes

2017-03-23 13:36 UTC, till commented on .travis.yml
> +  - find ~ -name pear -print
I think everything up until this line should be in an `install:` target.

2017-03-23 20:03 UTC, ashnazg commented on .travis.yml
> +  - find ~ -name pear -print
Does that make a difference on how the shell runs them?

2017-03-31 18:04 UTC, till commented on .travis.yml
> +  - find ~ -name pear -print
@ashnazg yeah, by not utilizing the targets, Travis-CI will execute its defaults. Needless roundtrips and cycles wasted. That's all! :)

2017-03-31 18:04 UTC, till approved these changes

2017-03-31 18:05 UTC, till commented
@ashnazg I just saw your other questions (sorry for the slow response). Is that still a problem?

My guess is that the `php-env` stuff probably does things a little different. But let me know if you need more help figuring this out.

2017-04-26 18:57 UTC, merged